import "inspectable.idl";
import "windows.ui.core.idl";
import "eventtoken.idl";

namespace Component
{
	runtimeclass Hen;

	[version(1.0)]
	[uuid(2b4fca62-b5a5-4d25-aa5d-6ed74ea97ece)]
	delegate HRESULT CluckHandler( 
		[in] Hen * sender,
		[in] int args);


	[version(1.0)]
	[uuid(710e2d1f-5382-498f-ba8c-33144ae16bc9)]
	interface IHen : IInspectable
	{
		HRESULT Cluck([in] CluckHandler * handler);
		
		HRESULT Clucking();
		//must be a matching pair 
		//token is just a 64bit number defined by idl
		[eventadd] HRESULT Clucked(
			[in] CluckHandler * handler,
			[out, retval] EventRegistrationToken * token);
		[eventremove] HRESULT Clucked([in] EventRegistrationToken token);

		//using Generic typeHandler
		//must be a matching pair 
		//token is just a 64bit number defined by idl
		[eventadd] HRESULT GenericClucked(
			[in] Windows.Foundation.TypedEventHandler<Hen *, int> * handler,
			[out, retval] EventRegistrationToken * token);
		[eventremove] HRESULT GenericClucked([in] EventRegistrationToken token);


		//Generic Collections and Iterators
		//IVectorView - readonly vector
		//IVector - full fledge
		[propget] HRESULT Brood([out, retval] Windows.Foundation.Collections.IVectorView<HSTRING> ** brood);

	}

	[version(1.0)]
	[uuid(86d68e2e-b05a-4d69-b642-490827eaa726)]
	interface IHenFactory :IInspectable
	{
		HRESULT CreateHen([in] INT32 eggs,
				[out][retval] Hen ** instance);
	}

	[version(1.0)]
	[uuid(e704abbb-dfdb-4e52-a0d8-5d4033b90ef0)]
	interface IHenStatics : IInspectable
	{
		[propget] HRESULT Layers([out][retval] INT32 * value);
	}

	[version(1.0)]
	[uuid(BB1AF9FE-D9D3-41F7-B1EA-F5AC77622911)]
	interface ILayer : IInspectable
	{
		[propget] HRESULT Eggs([out][retval] INT32 * value);
	}
	
	[version(1.0)]
	[activatable(1.0)]
	[activatable(IHenFactory, 1.0)]
	[static(IHenStatics, 1.0)]
	runtimeclass Hen
	{
		[default] interface IHen;
		interface ILayer;
	}
}